### ISSUE TITLE
Please identify the custom vmlinuz64 and initrd.img

### ISSUE THREAD

**Issue by ailispaw** [nlf/dhyve#3]
I found your custom boot2docker with your pull request, but the URLs in `download_boot2docker` scares me and someone probably.

I recommend you to add some comments or put them in the release page at nlf/boot2docker or here.

What do you think?

**Comment by nlf** [comment]
Probably a very good idea. I'll get them moved to the release page

**Comment by ailispaw** [comment]
And also I feel the same with silent install, too.
Could you remove `@` from `@install` in Makefile?

**Comment by nlf** [comment]
Also for the record (which this should be documented) all my custom boot2docker build is is a standard 1.7.0 build but with this patch merged https://github.com/boot2docker/boot2docker/pull/981

**Comment by nlf** [comment]
@ailispaw definitely, i think a lot of the @ prefixes can probably be removed, i only had most of them there because i was tired of scrolling so much while testing it :) feel free to make whatever changes you see fit. submit them in a PR if you want review on them or aren't sure about them for whatever reason

**Comment by ailispaw** [comment]
@nlf Thanks a lot.

**Comment by nlf** [comment]
Moved the kernel and initrd to a release, and tagged a 1.0.0, but it kinda messes up the whole submodule thing since you'd have to download the release (the source code, i mean) then initialize it as a git repo, then init the sub module and update it.

Maybe we should consider using homebrew to install xhyve?

**Comment by ailispaw** [comment]
Currently homebrew points to the old version of xhyve which isn't compatible with the current args of dhyve.
So it's still needed the sub module to work for a while and v1.0.0 looks good to me.

**Comment by ailispaw** [comment]
BTW,
I have a trouble with boot2docker v1.7.1 which is released yesterday.
How about your side?

**Comment by ailispaw** [comment]
I know it doesn't include your patch, but even boot2docker-xhyve doesn't work with boot2docker v1.7.1.
I'm going to investigate it.

**Comment by nlf** [comment]
When I tried building from master last week I had trouble too, but I didn't bother investigating. I also briefly experimented with using rancheros instead of boot2docker, but also had issues with that.

**Comment by ailispaw** [comment]
Thanks for the info. I will try to figure it out.

**Comment by ailispaw** [comment]
closing anyway.

**Comment by ailispaw** [comment]
FYI:
https://github.com/ailispaw/boot2docker-xhyve/issues/6
https://github.com/ailispaw/boot2docker/pull/1

**Comment by ailispaw** [comment]
Upgraded https://github.com/ailispaw/boot2docker-xhyve
Uploaded https://github.com/ailispaw/boot2docker/releases/tag/xhyve%2Fv1.7.1
It should be fine with dhyve, too.
