### ISSUE TITLE
dhyve vm can not access VPN'ed resources

### ISSUE THREAD

**Issue by lmb** [nlf/dhyve#44]
It seems dhyve does not cope well with Cisco AnyConnect based VPNs. Servers behind the VPN are pingable from the host, but not from the dhyve guest.

I'm assuming the host does not know that it should route between the bridge and the VPN. Any ideas on how to achieve this?

**Comment by nlf** [comment]
this would require a bit different network setup than what dhyve currently does.. i _think_ you'd have to set up a tun interface and tell xhyve (the virtualization software) to use that instead of the standard virtio-net interface that it currently uses. i'd have to do some research to figure out how to make this work.

**Comment by lmb** [comment]
Hi Nathan,

Thanks for your help. Did some more digging:
- The two relevant devices are `bridge100` and `utun0` (VPN)
- Packets coming in via `bridge100` and leaving to the public internet are properly NATed
- Packets coming in via `bridge100` and exiting to `utun0` still carry the internal, host-only IP address

Seems like there is a special case in virtio-net somewhere that makes the NAT happen. Any idea where that might be?

**Comment by nlf** [comment]
i honestly couldn't tell you. this sounds like something that we need to solve at the [xhyve](https://github.com/mist64/xhyve) level

**Comment by lmb** [comment]
Filed mist64/xhyve#84, maybe we can find out some more that way.

**Comment by nlf** [comment]
great, thanks for linking to it here. that'll be useful information
